AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline with Path Filter

Parameters:
  ConnectionArn:
    Type: String
    Description: CodeStar Connection ARN

Resources:
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cfn-path-filter-pipeline-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codeconnections:UseConnection
                  - codestar-connections:UseConnection
                Resource: !Ref ConnectionArn
              - Effect: Allow
                Action:
                  - s3:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - codebuild:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'cfn-path-filter-artifacts-${AWS::AccountId}'

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: cfn-path-filter-demo-pipeline
      PipelineType: V2
      ExecutionMode: QUEUED
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      
      Triggers:
        - ProviderType: CodeStarSourceConnection
          GitConfiguration:
            SourceActionName: Source
            Push:
              - Branches:
                  Includes:
                    - main
                FilePaths:
                  Includes:
                    - 'app/**'
                    - 'src/**'
                  Excludes:
                    - 'app/test/**'
      
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref ConnectionArn
                FullRepositoryId: toshiro3/codepipeline-path-filter-demo
                BranchName: main
                DetectChanges: 'true'
              OutputArtifacts:
                - Name: SourceArtifact
        
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Compute
                Owner: AWS
                Provider: Commands
                Version: '1'
              Configuration: {}
              InputArtifacts:
                - Name: SourceArtifact
              Commands:
                - echo "Build from CloudFormation"
                - ls -la

Outputs:
  PipelineName:
    Value: !Ref Pipeline
  PipelineArn:
    Value: !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${Pipeline}'
